### ISSUE TITLE
多级list数据存储问题

### ISSUE THREAD

**Issue by 900326** [huyongli/TigerDB#3]
![qq 20161207110141](https://cloud.githubusercontent.com/assets/11885751/20953247/e86ddf4a-bc6c-11e6-8e2b-c2bd63fed74c.png)
对于这样的省市县的多级list数据,我用下图的方式保存,获取,但是获取的集合,只有省份,省份下面的市集合,市下面的县集合都是空,(只能获取districtVos下面的id,district,而cityVos集合及cityVos下面的areaVos集合都是空),是我的存储方式不对还是不能这么存,
![image](https://cloud.githubusercontent.com/assets/11885751/20954502/e6362f7a-bc76-11e6-958c-02154b0e37fe.png)

**Comment by huyongli** [comment]
sorry，这个目前还不支持级联存储 @900326
